apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
data:
  HIVE_HOST: "hiveserver2-service"
  HIVE_PORT: "10000"
  HIVE_USERNAME: "hive"
  HIVE_DATABASE: "default"
  MLFLOW_TRACKING_URI: "file:/app/models/mlruns"