apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-training-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-training-listener
  template:
    metadata:
      labels:
        app: mlflow-training-listener
    spec:
      containers:
      - name: training-listener
        image: oliverxll/sdu-masters-se1-big-data:mlflow-server
        imagePullPolicy: Always
        command: ["python", "src/train_model.py"]
        envFrom:
        - configMapRef:
            name: mlflow-config
        - secretRef:
            name: mlflow-secret
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: mlflow-models-pvc