name: CI/CD weather-producer

# Workflow triggers
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - weather-producer
    paths:
      - "weather-producer-java/**"
  pull_request:
    branches:
      - main
      - weather-producer
    paths:
      - "weather-producer-java/**"

# Environment Variables
env:
  IMAGE_NAME: weather-producer # lower case
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # Authenticate with GitHub Container Registry, could be changed to use DockerHub
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Transform github repo owner to lowercase
      - name: Transform repo owner to lowercase
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

     # Cache Maven dependencies to avoid downloading them every build:
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    
      # Building and pushing application image
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: weather-producer-java
          file: weather-producer-java/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.OWNER_LOWER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}